// <auto-generated />
using System;
using FCG.Catalog.Infrastructure.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FCG.Catalog.Infrastructure.SqlServer.Migrations
{
    [DbContext(typeof(FcgCatalogDbContext))]
    [Migration("20251210014313_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FCG.Catalog.Domain.Catalog.Entities.LibraryGames.LibraryGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GameId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PurchaseDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("PurchasedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .HasDatabaseName("IX_LibraryGames_GameId");

                    b.HasIndex("GameId1");

                    b.HasIndex("LibraryId", "GameId")
                        .IsUnique()
                        .HasDatabaseName("UQ_LibraryGames_LibraryId_GameId");

                    b.ToTable("LibraryGames", "Catalog", t =>
                        {
                            t.HasCheckConstraint("CK_LibraryGame_Price", "PurchasePrice >= 0");
                        });
                });

            modelBuilder.Entity("FCG.Catalog.Domain.Catalog.Entity.Games.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_Games_Category");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Games_IsActive");

                    b.ToTable("Games", "Catalog", t =>
                        {
                            t.HasCheckConstraint("CK_Game_Price", "Price > 0");
                        });
                });

            modelBuilder.Entity("FCG.Catalog.Domain.Catalog.Entity.Libraries.Library", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Libraries_UserId");

                    b.ToTable("Libraries", "Catalog");
                });

            modelBuilder.Entity("FCG.Catalog.Domain.Catalog.Entity.Promotions.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .HasDatabaseName("IX_Promotions_GameId");

                    b.HasIndex("StartDate", "EndDate")
                        .HasDatabaseName("IX_Promotions_Dates");

                    b.ToTable("Promotions", "Catalog", t =>
                        {
                            t.HasCheckConstraint("CK_Promotion_Dates", "EndDate > StartDate");

                            t.HasCheckConstraint("CK_Promotion_Discount", "DiscountPercentage > 0 AND DiscountPercentage <= 100");
                        });
                });

            modelBuilder.Entity("FCG.Catalog.Domain.Catalog.Entities.LibraryGames.LibraryGame", b =>
                {
                    b.HasOne("FCG.Catalog.Domain.Catalog.Entity.Games.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FCG.Catalog.Domain.Catalog.Entity.Games.Game", null)
                        .WithMany("LibraryGames")
                        .HasForeignKey("GameId1");

                    b.HasOne("FCG.Catalog.Domain.Catalog.Entity.Libraries.Library", "Library")
                        .WithMany("LibraryGames")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FCG.Catalog.Domain.Catalog.ValueObjects.Price", "PurchasePrice", b1 =>
                        {
                            b1.Property<Guid>("LibraryGameId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PurchasePrice");

                            b1.HasKey("LibraryGameId");

                            b1.ToTable("LibraryGames", "Catalog");

                            b1.WithOwner()
                                .HasForeignKey("LibraryGameId");
                        });

                    b.Navigation("Game");

                    b.Navigation("Library");

                    b.Navigation("PurchasePrice")
                        .IsRequired();
                });

            modelBuilder.Entity("FCG.Catalog.Domain.Catalog.Entity.Games.Game", b =>
                {
                    b.OwnsOne("FCG.Catalog.Domain.Catalog.ValueObjects.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("GameId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Price");

                            b1.HasKey("GameId");

                            b1.ToTable("Games", "Catalog");

                            b1.WithOwner()
                                .HasForeignKey("GameId");
                        });

                    b.OwnsOne("FCG.Catalog.Domain.Catalog.ValueObjects.Title", "Title", b1 =>
                        {
                            b1.Property<Guid>("GameId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Title");

                            b1.HasKey("GameId");

                            b1.ToTable("Games", "Catalog");

                            b1.WithOwner()
                                .HasForeignKey("GameId");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("FCG.Catalog.Domain.Catalog.Entity.Promotions.Promotion", b =>
                {
                    b.HasOne("FCG.Catalog.Domain.Catalog.Entity.Games.Game", "Game")
                        .WithMany("Promotions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FCG.Catalog.Domain.Catalog.ValueObjects.Discount", "DiscountPercentage", b1 =>
                        {
                            b1.Property<Guid>("PromotionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("DiscountPercentage");

                            b1.HasKey("PromotionId");

                            b1.ToTable("Promotions", "Catalog");

                            b1.WithOwner()
                                .HasForeignKey("PromotionId");
                        });

                    b.Navigation("DiscountPercentage")
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("FCG.Catalog.Domain.Catalog.Entity.Games.Game", b =>
                {
                    b.Navigation("LibraryGames");

                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("FCG.Catalog.Domain.Catalog.Entity.Libraries.Library", b =>
                {
                    b.Navigation("LibraryGames");
                });
#pragma warning restore 612, 618
        }
    }
}
