<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsTestProject>true</IsTestProject>
		<SonarQubeExclude>true</SonarQubeExclude>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Bogus" />
		<PackageReference Include="Moq" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\src\FCG.Catalog.Domain\FCG.Catalog.Domain.csproj" />
	  <ProjectReference Include="..\..\src\FCG.Catalog.Infrastructure.Kafka\FCG.Catalog.Infrastructure.Kafka.csproj" />
	</ItemGroup>

</Project>
