<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>		
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="TestResults\**" />
	  <EmbeddedResource Remove="TestResults\**" />
	  <None Remove="TestResults\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" />
		<PackageReference Include="FluentAssertions" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="xunit" />
		<PackageReference Include="xunit.runner.visualstudio" />
		<PackageReference Include="System.Net.Http" />
		<PackageReference Include="System.Text.RegularExpressions" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Domain\ValueObjects\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\src\FCG.Catalog.Application\FCG.Catalog.Application.csproj" />
	  <ProjectReference Include="..\..\src\FCG.Catalog.Domain\FCG.Catalog.Domain.csproj" />
	  <ProjectReference Include="..\..\src\FCG.Catalog.Infrastructure.Kafka\FCG.Catalog.Infrastructure.Kafka.csproj" />
	  <ProjectReference Include="..\FCG.Catalog.CommomTestUtilities\FCG.Catalog.CommomTestUtilities.csproj" />
	</ItemGroup>

</Project>
