apiVersion: v1
kind: ConfigMap
metadata:
  name: fcg-catalog-config
  namespace: fcg-catalog
  labels:
    app.kubernetes.io/name: fcg-catalog
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  KafkaSettings__BootstrapServers: "fcg-kafka.servicebus.windows.net:9093"
  KafkaSettings__ClientId: "fcg-catalog"
  KafkaSettings__SaslUsername: "$ConnectionString"
  KafkaSettings__UseSaslSsl: "true"
  RedisSettings__InstanceName: "fcg-catalog:"
  RedisSettings__DefaultTtlSeconds: "60"
  ElasticsearchSettings__IndexName: "games"
  ElasticsearchSettings__Username: ""
  ElasticsearchSettings__Password: ""
  Observability__ServiceName: "FCG.Catalog"
  Observability__EnableOtlpExporter: "false"
  Observability__OtlpEndpoint: ""
  JwtSettings__Issuer: "FCG-User"
  JwtSettings__Audience: "FCG-Client"

