apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fcg-catalog-hpa
  namespace: fcg-catalog
  labels:
    app.kubernetes.io/name: fcg-catalog
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fcg-catalog
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
