//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCG.Catalog.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FCG.Catalog.Messages.ResourceMessages", typeof(ResourceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount must be between 0 and 100..
        /// </summary>
        public static string DiscountMustBeBetweenZeroAndHundred {
            get {
                return ResourceManager.GetString("DiscountMustBeBetweenZeroAndHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game category type is invalid..
        /// </summary>
        public static string GameCategoryIsRequired {
            get {
                return ResourceManager.GetString("GameCategoryIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game category must be less than 100 characters..
        /// </summary>
        public static string GameCategoryMaxLength {
            get {
                return ResourceManager.GetString("GameCategoryMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum price must be greater than or equal to the minimum price..
        /// </summary>
        public static string GameMaxPriceMustBeGreaterThanMinPrice {
            get {
                return ResourceManager.GetString("GameMaxPriceMustBeGreaterThanMinPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game with name {0} already exists..
        /// </summary>
        public static string GameNameAlreadyExists {
            get {
                return ResourceManager.GetString("GameNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game name is required..
        /// </summary>
        public static string GameNameIsRequired {
            get {
                return ResourceManager.GetString("GameNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game with Not Found.
        /// </summary>
        public static string GameNotFound {
            get {
                return ResourceManager.GetString("GameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game price must be greater than zero..
        /// </summary>
        public static string GamePriceMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("GamePriceMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title must be more than 255 characteres.
        /// </summary>
        public static string GameTitleMaxLength {
            get {
                return ResourceManager.GetString("GameTitleMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title must be more than three characters long.
        /// </summary>
        public static string GameTitleMinLength {
            get {
                return ResourceManager.GetString("GameTitleMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Data.
        /// </summary>
        public static string GameValidateData {
            get {
                return ResourceManager.GetString("GameValidateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid access level..
        /// </summary>
        public static string InvalidAccessLevel {
            get {
                return ResourceManager.GetString("InvalidAccessLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library already exists for user {0}..
        /// </summary>
        public static string LibraryAlreadyExists {
            get {
                return ResourceManager.GetString("LibraryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact support..
        /// </summary>
        public static string PleaseContactSupport {
            get {
                return ResourceManager.GetString("PleaseContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price cannot be a negative value..
        /// </summary>
        public static string PriceCannotBeNegative {
            get {
                return ResourceManager.GetString("PriceCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be on or after the start date..
        /// </summary>
        public static string PromotionEndDateMustBeAfterStartDate {
            get {
                return ResourceManager.GetString("PromotionEndDateMustBeAfterStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred!.
        /// </summary>
        public static string UnexpectedErrorOccurred {
            get {
                return ResourceManager.GetString("UnexpectedErrorOccurred", resourceCulture);
            }
        }
    }
}
