//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCG.Catalog.Messages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FCG.Catalog.Messages.ResourceMessages", typeof(ResourceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string GamePriceMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("GamePriceMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        public static string InvalidAccessLevel {
            get {
                return ResourceManager.GetString("InvalidAccessLevel", resourceCulture);
            }
        }
        
        public static string GameMaxPriceMustBeGreaterThanMinPrice {
            get {
                return ResourceManager.GetString("GameMaxPriceMustBeGreaterThanMinPrice", resourceCulture);
            }
        }
        
        public static string GameNameAlreadyExists {
            get {
                return ResourceManager.GetString("GameNameAlreadyExists", resourceCulture);
            }
        }
        
        public static string GameNameIsRequired {
            get {
                return ResourceManager.GetString("GameNameIsRequired", resourceCulture);
            }
        }
        
        public static string GameCategoryIsRequired {
            get {
                return ResourceManager.GetString("GameCategoryIsRequired", resourceCulture);
            }
        }
        
        public static string GameCategoryMaxLength {
            get {
                return ResourceManager.GetString("GameCategoryMaxLength", resourceCulture);
            }
        }
        
        public static string GameTitleMinLength {
            get {
                return ResourceManager.GetString("GameTitleMinLength", resourceCulture);
            }
        }
        
        public static string GameTitleMaxLength {
            get {
                return ResourceManager.GetString("GameTitleMaxLength", resourceCulture);
            }
        }
        
        public static string GameValidateData {
            get {
                return ResourceManager.GetString("GameValidateData", resourceCulture);
            }
        }
        
        public static string PromotionEndDateMustBeAfterStartDate {
            get {
                return ResourceManager.GetString("PromotionEndDateMustBeAfterStartDate", resourceCulture);
            }
        }
        
        public static string UnexpectedErrorOccurred {
            get {
                return ResourceManager.GetString("UnexpectedErrorOccurred", resourceCulture);
            }
        }
        
        public static string PleaseContactSupport {
            get {
                return ResourceManager.GetString("PleaseContactSupport", resourceCulture);
            }
        }
        
        public static string GameNotFound {
            get {
                return ResourceManager.GetString("GameNotFound", resourceCulture);
            }
        }
        
        public static string DiscountMustBeBetweenZeroAndHundred {
            get {
                return ResourceManager.GetString("DiscountMustBeBetweenZeroAndHundred", resourceCulture);
            }
        }
        
        public static string PriceCannotBeNegative {
            get {
                return ResourceManager.GetString("PriceCannotBeNegative", resourceCulture);
            }
        }
        
        public static string LibraryAlreadyExists {
            get {
                return ResourceManager.GetString("LibraryAlreadyExists", resourceCulture);
            }
        }
        
        public static string GameWithPromotion {
            get {
                return ResourceManager.GetString("GameWithPromotion", resourceCulture);
            }
        }
    }
}
