<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<PreserveCompilationContext>true</PreserveCompilationContext>
	<InternalsVisibleTo>FCG.Catalog.IntegratedTests</InternalsVisibleTo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Elmah.Io.AspNetCore" Version="5.3.88" />
    <PackageReference Include="Elmah.Io.Extensions.Logging" Version="5.3.67" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.22" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.22">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Serilog.Sinks.ElmahIo" Version="5.3.58" />

    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\FCG.Catalog.Infrastructure.Auth\FCG.Catalog.Infrastructure.Auth.csproj" />
    <ProjectReference Include="..\FCG.Catalog.Application\FCG.Catalog.Application.csproj" />
    <ProjectReference Include="..\FCG.Catalog.Infrastructure.SqlServer\FCG.Catalog.Infrastructure.SqlServer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FCG.Catalog.Infrastructure.Kafka\FCG.Catalog.Infrastructure.Kafka.csproj" />
  </ItemGroup>

</Project>
